import { DESIGN_TOKEN_SCHEMA_VERSION } from "./schema.js";

const token = (name, cssVariable, type, tier, value, description) => ({
  schemaVersion: DESIGN_TOKEN_SCHEMA_VERSION,
  name,
  cssVariable,
  type,
  tier,
  value,
  description,
});

export const defaultDesignTokens = {
  schemaVersion: DESIGN_TOKEN_SCHEMA_VERSION,
  tokens: [
    token(
      "color.ink",
      "--of-color-ink",
      "color",
      "global",
      "#111318",
      "Primary text and dark surface color.",
    ),
    token(
      "color.paper",
      "--of-color-paper",
      "color",
      "global",
      "#ffffff",
      "Primary light surface color.",
    ),
    token(
      "color.orange-500",
      "--of-color-orange-500",
      "color",
      "global",
      "#ff5a1f",
      "Core OpenForge orange.",
    ),
    token(
      "color.action",
      "--of-color-action",
      "color",
      "semantic",
      "{color.orange-500}",
      "Interactive action and focus color.",
    ),
    token(
      "color.background",
      "--of-color-background",
      "color",
      "semantic",
      "{color.paper}",
      "Default page background.",
    ),
    token(
      "space.2",
      "--of-space-2",
      "dimension",
      "global",
      "0.5rem",
      "Compact spacing step.",
    ),
    token(
      "space.4",
      "--of-space-4",
      "dimension",
      "global",
      "1rem",
      "Base spacing step.",
    ),
    token(
      "space.8",
      "--of-space-8",
      "dimension",
      "global",
      "2rem",
      "Large spacing step.",
    ),
    token(
      "space.16",
      "--of-space-16",
      "dimension",
      "global",
      "4rem",
      "Section spacing step.",
    ),
    token(
      "space.section",
      "--of-space-section",
      "dimension",
      "semantic",
      "{space.16}",
      "Default vertical section padding.",
    ),
    token(
      "radius.control",
      "--of-radius-control",
      "radius",
      "semantic",
      "0.375rem",
      "Default control corner radius.",
    ),
    token(
      "radius.card",
      "--of-radius-card",
      "radius",
      "semantic",
      "1.25rem",
      "Default card corner radius.",
    ),
    token(
      "font.body",
      "--of-font-body",
      "font-family",
      "semantic",
      "Arial, sans-serif",
      "Default readable body typeface.",
    ),
    token(
      "font.size-body",
      "--of-font-size-body",
      "font-size",
      "semantic",
      "1rem",
      "Default body text size.",
    ),
    token(
      "font.weight-strong",
      "--of-font-weight-strong",
      "font-weight",
      "semantic",
      "700",
      "Strong text weight.",
    ),
    token(
      "line-height.body",
      "--of-line-height-body",
      "line-height",
      "semantic",
      "1.6",
      "Default body line height.",
    ),
    token(
      "shadow.card",
      "--of-shadow-card",
      "shadow",
      "semantic",
      "0 1rem 3rem rgb(17 19 24 / 0.12)",
      "Default elevated card shadow.",
    ),
  ],
};
