export const manifest = {
  schemaVersion: 1,
  id: "openforge-theme.healthcare",
  name: "Healthcare",
  version: "1.0.0",
  description:
    "A calm, high-contrast theme for clinics and medical practices: services, care-team profiles, patient FAQs, notices, and appointment calls to action.",
  regions: [
    {
      key: "page-body",
      label: "Page body",
      allowedBlockIds: [
        "openforge-cms.hero",
        "openforge-cms.banner",
        "openforge-cms.alert",
        "openforge-cms.heading",
        "openforge-cms.rich-text",
        "openforge-cms.image",
        "openforge-cms.icon-box",
        "openforge-cms.feature-list",
        "openforge-cms.card",
        "openforge-cms.columns",
        "openforge-cms.stats-row",
        "openforge-cms.team-member",
        "openforge-cms.testimonial",
        "openforge-cms.rating",
        "openforge-cms.accordion",
        "openforge-cms.timeline",
        "openforge-cms.data-table",
        "openforge-cms.logo-cloud",
        "openforge-cms.pricing",
        "openforge-cms.badge",
        "openforge-cms.video",
        "openforge-cms.cta",
        "openforge-cms.button",
        "openforge-cms.divider",
        "openforge-cms.spacer",
        "openforge-cms.navbar",
        "openforge-cms.breadcrumbs",
        "openforge-cms.tabs",
        "openforge-cms.comparison-table",
        "openforge-cms.location-card",
        "openforge-cms.contact-form",
      ],
    },
    {
      key: "post-body",
      label: "Post body",
      allowedBlockIds: [
        "openforge-cms.heading",
        "openforge-cms.rich-text",
        "openforge-cms.image",
        "openforge-cms.alert",
        "openforge-cms.feature-list",
        "openforge-cms.card",
        "openforge-cms.accordion",
        "openforge-cms.data-table",
        "openforge-cms.testimonial",
        "openforge-cms.badge",
        "openforge-cms.cta",
        "openforge-cms.button",
        "openforge-cms.divider",
      ],
    },
    {
      key: "footer",
      label: "Footer",
      allowedBlockIds: ["openforge-cms.footer", "openforge-cms.social-links"],
    },
  ],
  templateNames: ["page", "post", "notFound"],
  // Identity: a deep clinical teal accent on a soft mint-tinted paper, with
  // generously rounded cards and roomy line height. The accent is dark
  // enough to clear WCAG AA (5.2:1) against both paper and background, so
  // links and buttons stay legible without a second "accessible" variant.
  defaultTokenOverrides: {
    "color.ink": "#122a31",
    "color.paper": "#ffffff",
    "color.background": "#f4f9f8",
    "color.action": "#0b7a69",
    "radius.card": "1rem",
    "radius.control": "0.5rem",
    "font.body": "Inter, Segoe UI, Helvetica Neue, Arial, sans-serif",
    "font.size-body": "1.0625rem",
    "line-height.body": "1.7",
    "font.weight-strong": "600",
    "space.section": "5rem",
    "shadow.card": "0 0.75rem 2rem rgb(11 122 105 / 0.12)",
  },
};
