export const manifest = {
  schemaVersion: 1,
  id: "openforge-theme.magazine",
  name: "Magazine",
  version: "1.0.0",
  description:
    "A high-contrast editorial theme for magazines, journals, and long-form blogs: black ink on white paper, one assertive red, square corners, and a dense reading column.",
  regions: [
    {
      key: "masthead",
      label: "Masthead",
      allowedBlockIds: [
        "openforge-cms.banner",
        "openforge-cms.marquee-text",
        "openforge-cms.heading",
        "openforge-cms.badge",
        "openforge-cms.button",
        "openforge-cms.divider",
      ],
    },
    {
      key: "page-body",
      label: "Page body",
      allowedBlockIds: [
        "openforge-cms.hero",
        "openforge-cms.gradient-heading",
        "openforge-cms.heading",
        "openforge-cms.rich-text",
        "openforge-cms.image",
        "openforge-cms.badge",
        "openforge-cms.avatar-item",
        "openforge-cms.avatar-group",
        "openforge-cms.marquee-text",
        "openforge-cms.feature-list",
        "openforge-cms.divider",
        "openforge-cms.spacer",
        "openforge-cms.columns",
        "openforge-cms.card",
        "openforge-cms.testimonial",
        "openforge-cms.banner",
        "openforge-cms.alert",
        "openforge-cms.cta",
        "openforge-cms.button",
        "openforge-cms.stats-row",
        "openforge-cms.stat",
        "openforge-cms.timeline",
        "openforge-cms.timeline-step",
        "openforge-cms.accordion",
        "openforge-cms.faq-item",
        "openforge-cms.data-table",
        "openforge-cms.team-member",
        "openforge-cms.icon-box",
        "openforge-cms.spotlight-card",
        "openforge-cms.video",
      ],
    },
    {
      key: "post-body",
      label: "Post body",
      allowedBlockIds: [
        "openforge-cms.rich-text",
        "openforge-cms.heading",
        "openforge-cms.gradient-heading",
        "openforge-cms.image",
        "openforge-cms.badge",
        "openforge-cms.avatar-item",
        "openforge-cms.avatar-group",
        "openforge-cms.testimonial",
        "openforge-cms.feature-list",
        "openforge-cms.divider",
        "openforge-cms.spacer",
        "openforge-cms.columns",
        "openforge-cms.marquee-text",
        "openforge-cms.alert",
        "openforge-cms.data-table",
        "openforge-cms.video",
        "openforge-cms.button",
        "openforge-cms.cta",
      ],
    },
    {
      key: "footer",
      label: "Footer",
      allowedBlockIds: ["openforge-cms.footer"],
    },
  ],
  templateNames: ["page", "post", "notFound"],
  defaultTokenOverrides: {
    // Newsprint contrast: near-black ink on pure white paper.
    "color.ink": "#0b0b0c",
    "color.paper": "#ffffff",
    "color.background": "#ffffff",
    // One assertive accent, used for section kickers, rules, and links.
    "color.orange-500": "#d6002a",
    // Slightly deeper red for interactive text and focus rings (~6.2:1 on white).
    "color.action": "#c40026",
    // Serif-leaning body face for long-form reading, with real system fallbacks.
    "font.body":
      '"Iowan Old Style", Charter, "Source Serif 4", Georgia, "Times New Roman", serif',
    "font.size-body": "1.0625rem",
    "font.weight-strong": "800",
    // Denser leading than the default 1.6 — magazine column, not marketing page.
    "line-height.body": "1.45",
    // Print sensibility: hard corners, no floating cards.
    "radius.card": "0",
    "radius.control": "0",
    "shadow.card": "none",
    // Tighter section rhythm so a front page fits more stories above the fold.
    "space.section": "3.25rem",
  },
};
