export const manifest = {
  schemaVersion: 1,
  id: "openforge-theme.default",
  name: "Default",
  version: "1.0.0",
  description:
    "The default OpenForge CMS theme: a clean, accessible starting point.",
  regions: [
    {
      key: "page-body",
      label: "Page body",
      allowedBlockIds: [
        "openforge-cms.hero",
        "openforge-cms.rich-text",
        "openforge-cms.image",
        "openforge-cms.cta",
        "openforge-cms.columns",
        "openforge-cms.heading",
        "openforge-cms.button",
        "openforge-cms.spacer",
        "openforge-cms.divider",
        "openforge-cms.icon-box",
        "openforge-cms.alert",
        "openforge-cms.video",
        "openforge-cms.testimonial",
        "openforge-cms.pricing",
        "openforge-cms.team-member",
        "openforge-cms.stats-row",
        "openforge-cms.accordion",
        "openforge-cms.badge",
        "openforge-cms.card",
        "openforge-cms.rating",
        "openforge-cms.progress",
        "openforge-cms.banner",
        "openforge-cms.logo-cloud",
        "openforge-cms.timeline",
        "openforge-cms.avatar-group",
      ],
    },
    {
      key: "post-body",
      label: "Post body",
      allowedBlockIds: [
        "openforge-cms.rich-text",
        "openforge-cms.image",
        "openforge-cms.cta",
        "openforge-cms.heading",
        "openforge-cms.button",
        "openforge-cms.divider",
        "openforge-cms.video",
        "openforge-cms.alert",
        "openforge-cms.pricing",
        "openforge-cms.badge",
        "openforge-cms.card",
      ],
    },
    {
      key: "footer",
      label: "Footer",
      allowedBlockIds: ["openforge-cms.footer"],
    },
  ],
  templateNames: ["page", "post", "notFound"],
  defaultTokenOverrides: {},
};
