export const manifest = {
  schemaVersion: 1,
  id: "openforge-theme.saas",
  name: "SaaS",
  version: "1.0.0",
  description:
    "A conversion-focused theme for SaaS and startup marketing sites: hero, social proof, feature, pricing, and FAQ sections in an indigo-violet identity.",
  regions: [
    {
      key: "header",
      label: "Header",
      allowedBlockIds: [
        "openforge-cms.banner",
        "openforge-cms.marquee-text",
        "openforge-cms.badge",
        "openforge-cms.button",
      ],
    },
    {
      key: "page-body",
      label: "Page body",
      allowedBlockIds: [
        "openforge-cms.hero",
        "openforge-cms.gradient-heading",
        "openforge-cms.heading",
        "openforge-cms.rich-text",
        "openforge-cms.feature-list",
        "openforge-cms.icon-box",
        "openforge-cms.spotlight-card",
        "openforge-cms.card",
        "openforge-cms.columns",
        "openforge-cms.pricing",
        "openforge-cms.testimonial",
        "openforge-cms.avatar-group",
        "openforge-cms.rating",
        "openforge-cms.stats-row",
        "openforge-cms.logo-cloud",
        "openforge-cms.accordion",
        "openforge-cms.timeline",
        "openforge-cms.team-member",
        "openforge-cms.data-table",
        "openforge-cms.carousel",
        "openforge-cms.cta",
        "openforge-cms.banner",
        "openforge-cms.marquee-text",
        "openforge-cms.button",
        "openforge-cms.image",
        "openforge-cms.video",
        "openforge-cms.badge",
        "openforge-cms.alert",
        "openforge-cms.progress",
        "openforge-cms.divider",
        "openforge-cms.spacer",
      ],
    },
    {
      key: "post-body",
      label: "Post body",
      allowedBlockIds: [
        "openforge-cms.heading",
        "openforge-cms.rich-text",
        "openforge-cms.image",
        "openforge-cms.video",
        "openforge-cms.feature-list",
        "openforge-cms.data-table",
        "openforge-cms.card",
        "openforge-cms.testimonial",
        "openforge-cms.accordion",
        "openforge-cms.alert",
        "openforge-cms.badge",
        "openforge-cms.button",
        "openforge-cms.cta",
        "openforge-cms.divider",
        "openforge-cms.spacer",
      ],
    },
    {
      key: "footer",
      label: "Footer",
      allowedBlockIds: ["openforge-cms.footer"],
    },
  ],
  templateNames: ["page", "post", "notFound"],
  defaultTokenOverrides: {
    "color.ink": "#14142b",
    "color.paper": "#ffffff",
    "color.background": "#f7f7fb",
    "color.orange-500": "#6d5efc",
    "color.action": "#5a4bf0",
    "space.section": "6rem",
    "radius.card": "1rem",
    "radius.control": "0.5rem",
    "font.body": "Inter, Segoe UI, Helvetica Neue, Arial, sans-serif",
    "font.size-body": "1.0625rem",
    "font.weight-strong": "600",
    "line-height.body": "1.65",
    "shadow.card": "0 1.5rem 3rem rgb(20 20 43 / 0.1)",
  },
};
